---
description: >
  Geekdoc is a simple Hugo theme for documentations. It is intentionally designed as a fast and lean theme
  and may not fit the requirements of complex projects. If a more feature-complete theme is required
  there are a lot of good alternatives out there.
images:
  - "socialmedia2.png"

geekdocToC: 3
geekdocTagsToMenu: true

geekdocRepo: https://github.com/thegeeklab/hugo-geekdoc
geekdocEditPath: edit/main/exampleSite

geekdocSearch: true
geekdocSearchShowParent: true
geekdocSearchShowDescription: true

geekdocLegalNotice: https://thegeeklab.de/legal-notice/#contact-information
geekdocPrivacyPolicy: https://thegeeklab.de/legal-notice/#privacy-policy

geekdocImageLazyLoading: true
geekdocDarkModeDim: true
